# datasets from the path `sunbird/salt` are public while the rest are private to Sunbird.
training_args:
  output_dir: "{dir_name}"
  evaluation_strategy: steps
  eval_steps: 100
  save_steps: 100
  logging_steps: 50
  warmup_steps: 100
  gradient_accumulation_steps: {gradient_accumulation_steps}
  learning_rate: 3.0e-4  # Include decimal point to parse as float
  per_device_train_batch_size: {train_batch_size}
  per_device_eval_batch_size: {eval_batch_size}
  weight_decay: 0.01
  save_total_limit: 3
  max_steps: 1000
  predict_with_generate: True
  fp16: {fp16}
  logging_dir: "{dir_name}"
  load_best_model_at_end: True
  metric_for_best_model: loss
  label_smoothing_factor: 0.1

other_args:
  mlflow_run_name: translate-many-eng
  max_input_length: 150
  eval_pretrained_model: False
  early_stopping_patience: 5
  data_dir: .
  model_checkpoint: Helsinki-NLP/opus-mt-mul-en

common_source: &common_source
  type: text
  language: [ach,lgg,lug,nyn,teo] # for monolingual, provide only one language code
  preprocessing:
    - clean_text

common_target: &common_target
  type: text
  language: [eng]
  preprocessing:
    - clean_text
    - match_target_sentence_format_to_source

datasets:
  train:
    huggingface_load:
        - path: sunbird/salt
          name: text-all
          split: train
        - path: Sunbird/external_mt_datasets
          name: ai4d.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: flores200.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: lafand-en-lug-combined.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: lafand-en-luo-combined.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: mozilla_110.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: mt560_ach.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: mt560_lug.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: mt560_nyn.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_from-eng-google.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_from-lug-google.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_ach_en_14_3_23.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_en_many_30_3.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_lug_en_14_3_23.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_wiki_en_ach_30_3.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_wiki_en_lgg_30_3.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_wiki_en_lug_30_3.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_wiki_en_nyn_30_3.parquet
          split: train
        - path: Sunbird/external_mt_datasets
          name: bt_wiki_en_teo_30_3.parquet
          split: train
    source: *common_source
    target: *common_target
    shuffle: True

  validation:
    huggingface_load:
        - path: sunbird/salt
          name: text-all
          split: dev  # optionally use a slice, e.g. dev[:10] for a quick test
    source: *common_source
    target: *common_target